services:
  # PostgreSQL database
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: termquestgenesis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=termquestgenesis
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      database:
        condition: service_healthy

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data: